id: 7741e46a-5685-4479-8f25-ab941a711d80
name: StashPay
links:
  website: https://stashpay.me/
  Github: https://github.com/onionmill/stashpay/

category: wallet

original_language:
  - en

tags:
  - bitcoin
  - payments
